Shoose/urls.py
from django.contrib import admin
from django.urls import path, include
from main import views

from django.conf.urls.static import static
from django.conf import settings

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', views.index, name='index'),
    path('nike/', views.nike, name='nike'),
    path('converse/', views.converse, name='converse'),
    path('users/', include('user.urls')),

]

urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

user/urls.py
from django.urls import path
from .views import JoinView, LoginView, logout

app_name = 'User'

urlpatterns =[
    path('signup', JoinView.as_view(), name='signup'),
    path('login', LoginView.as_view(), name='login'),
    path('logout', logout, name='logout'),
]

main/models.py
from django.db import models
from PIL import Image
class Post(models.Model):
    brand = models.CharField('BRAND', max_length=10)
    title = models.CharField(verbose_name='TITLE', max_length=50)
    price = models.IntegerField(null=True)
    date = models.CharField(max_length=100, null=True)
    date_int = models.IntegerField(null=True)
    image = models.ImageField(blank=True, null=True)

    def __unicode__(self):
        return self.title

    class Meta :
        db_table = 'search_lists'

user/models.py
from django.db import models

class User(models.Model):
    username = models.CharField(max_length=20, primary_key=True, verbose_name='사용자명')
    email = models.EmailField(max_length=50, verbose_name='비밀번호')
    password = models.CharField(max_length=20)

    def __str__(self):
        return self.username

    class Meta:
        db_table = 'users'

user/forms.py
from django import forms
from django.contrib.auth.hashers import check_password

from .models import User

# 회원가입 폼
class UserJoinForm(forms.Form):
    username = forms.CharField(
        label='이름',
        widget=forms.TextInput(attrs={'class': 'form-control'})
    )

    password = forms.CharField(
        label='비밀번호',
        widget=forms.PasswordInput(attrs={'class':'form-control'})
    )

    re_password = forms.CharField(
        label='비밀번호 확인',
        widget=forms.PasswordInput(attrs={'class':'form-control'})
    )

    email = forms.EmailField(
        label='이메일',
        widget=forms.EmailInput(attrs={'class':'form-control'})
    )


    def clean(self):
        # 요청파라미터값 조회
        cleaned_data = super().clean() #dict변환
        username = cleaned_data.get('username')
        email = cleaned_data.get('email')
        password = cleaned_data.get('password')
        re_password = cleaned_data.get('re_password')
        #password == repassword
        if password != re_password:
            self.add_error('password','비밀번호가 다릅니다.')
            self.add_error('re_password','비밀번호가 다릅니다.')

        #이메일 중복 체크
        try:
            User.objects.get(pk=username)
            self.add_error('username', '이미 가입된 이름 입니다.')
        except:
            pass


class LoginForm(forms.Form):
    username = forms.CharField(
        label='Username',
        widget=forms.TextInput(attrs={'class':'form-control'})
    )
    password = forms.CharField(
        label='비밀번호',
        widget=forms.PasswordInput(attrs={'class':'form-control'})
    )
    def clean(self):
        cleaned_data = super().clean() #부모에 있는 값을 clean으로 받아오기
        username = cleaned_data.get('username')
        password = cleaned_data.get('password')
        try:
            user = User.objects.get(pk=username)
            if not check_password(password, user.password):
                self.add_error('password','비밀번호가 틀렸습니다..')
        except:
            self.add_error('username','가입하지 않은 아이디입니다.')

main/views.py
from django.shortcuts import render
from .models import Post

import json
from django.http import HttpResponse, JsonResponse
import requests
from bs4 import BeautifulSoup
from django.views import View

def index(request):
    posts = Post.objects.all().order_by('date_int')
    return render(request, 'main/index.html', {
        'posts':posts,
    })

def nike(request):
    posts = Post.objects.all().order_by('date_int')
    return render(request, 'main/nike.html', {
        'posts':posts,
    })
def converse(request):
    posts = Post.objects.all().order_by('date_int')
    return render(request, 'main/converse.html', {
        'posts':posts,
    })

user/views.py
from django.shortcuts import render, redirect
from django.views.generic import FormView
# 패스워드 암호화 해주는 함수.
from django.contrib.auth.hashers import make_password
from .forms import UserJoinForm, LoginForm
from .models import User

# Create your views here.
# 가입처리
class JoinView(FormView):
    template_name = 'User/signup.html'
    form_class = UserJoinForm
    success_url = '/'

    def form_valid(self, form):
        cleaned_data = form.cleaned_data  # dict
        email = cleaned_data.get('email')
        password = make_password(cleaned_data.get('password'))  # 암호화
        username = cleaned_data.get('username')
        user = User(email=email, password=password, username=username)
        user.save()

        return super().form_valid(form)


# 로그인 처리 View
class LoginView(FormView):
    template_name = 'User/login.html'
    form_class = LoginForm
    success_url = '/'
    # 메인으로
    def form_valid(self, form):
        cleaned_data = form.cleaned_data
        username = cleaned_data.get('username')
        # db에 저장되어 있는 email
        # Session객체-dictionary 형태:key-value쌍이 필요
        # 로그인 -> session에 로그인 여부를 확인할 수 있는 체크값을 넣어둔다.
        self.request.session['User'] = username
        # request: HttpRequest(사용자 HTTP 요청정보)
        return super().form_valid(form)


# 로그 아웃
def logout(request):
    request.session.clear()

    return redirect('/')

main/templates/main/base.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">

    <title>Title</title>
    <link rel="stylesheet" href="{% static 'css/base.css' %}">
    <link media="only screen and (max-device-width: 800px)" rel="stylesheet" href="{% static 'css/pad_base.css' %}">
    <link media="only screen and (max-device-width: 600px)" rel="stylesheet" href="{% static 'css/mobile_base.css' %}">

</head>
<body>
    <nav class="navbar navbar-expand-lg navbar-light fixed-top" id="mainNav">
        <div class="container">
            <ul class="navbar-nav ml-auto">
              {% if request.session.User %}
              <li class="nav-item">
                <a class="nav-link" href="{% url 'index' %}">Home</a>
              </li>
              <li class="nav-item">
                  <a class="nav-link" href="{% url 'User:logout' %}">Logout</a>
              </li>
              <li>
                  <a class="nav-text">Welcome</a>
              </li>
              {% else %}
              <li class="nav-item">
                <a class="nav-link" href={% url 'index' %}>Home</a>
              </li>
              <li class="nav-item">
                <a class="nav-link" href="{% url 'User:login' %}">Login</a>
              </li>
              <li class="nav-item">
                <a class="nav-link" href="{% url 'User:signup' %}">Sign Up</a>
              </li>
              {% endif %}
            </ul>
        </div>
    </nav>

    <nav class="navbar navbar-expand-lg navbar-light fixed-top" id="subNav">
        <div class="container">
            <ul class="navbar-nav ml-auto">
              <li class="nav-item">
                <a class="nav-link" href="{% url 'index' %}">All</a>
              </li>
              <li class="nav-item">
                  <a class="nav-link" href="{% url 'nike' %}">Nike</a>
              </li>
              <li class="nav-item">
                  <a class="nav-link" href="{% url 'converse' %}">Converse</a>
              </li>
            </ul>
        </div>
    </nav>
{% block content %}

{% endblock %}
    <div class="footer">
        <div class="row">

                <p class="copyright text-muted">Create This Website 2021</p>

        </div>
    </div>
</body>

</html>

main/templates/main/converse.html
{% extends 'main/base.html' %}

{% block content %}
<div class="content_list">
{% for post in posts %}
    {% if post.brand == 'Converse' %}
        <div class="content" onclick="location.href='https://www.converse.co.kr/category/launch-calendar?pageSize=200&type=upcoming&activeDate=date-filter:AFTER'">
            <img src="{{ post.image }}" alt="" height="600" class="image">
            <h1 class="brand">{{ post.brand }}</h1>
            <p class="title">{{ post.title }}</p>
            <p class="date">{{ post.date }}</p>
        </div>
    {% elif post.brand != 'Nike' and post.brand != 'Converse' %}
        <p class="None_text">예정중인 상품이 없습니다.</p>
    {% endif %}
{% endfor %}
</div>

{% endblock %}

main/templates/main/index.html
{% extends 'main/base.html' %}

{% block content %}
<div class="content_list">
{% for post in posts %}
    {% if post.brand == 'Nike' %}
        <div class="content" onclick="location.href='https://www.nike.com/kr/launch/?type=upcoming&activeDate=date-filter:AFTER'">
            <img src="{{ post.image }}" alt="" height="600" class="image">
            <h1 class="brand">{{ post.brand }}</h1>
            <p class="title">{{ post.title }}</p>
            <p class="date">{{ post.date }}</p>
        </div>
    {% elif post.brand == 'Converse' %}
        <div class="content" onclick="location.href='https://www.converse.co.kr/category/launch-calendar?pageSize=200&type=upcoming&activeDate=date-filter:AFTER'">
            <img src="{{ post.image }}" alt="" height="600" class="image">
            <h1 class="brand">{{ post.brand }}</h1>
            <p class="title">{{ post.title }}</p>
            <p class="date">{{ post.date }}</p>
        </div>
    {% endif %}
{% endfor %}
</div>

{% endblock %}

main/templates/main/nike.html
{% extends 'main/base.html' %}

{% block content %}
<div class="content_list">
{% for post in posts %}
    {% if post.brand == 'Nike' %}
        <div class="content" onclick="location.href='https://www.nike.com/kr/launch/?type=upcoming&activeDate=date-filter:AFTER'">
            <img src="{{ post.image }}" alt="" height="600" class="image">
            <h1 class="brand">{{ post.brand }}</h1>
            <p class="title">{{ post.title }}</p>
            <p class="date">{{ post.date }}</p>
        </div>
    {% elif post.brand != 'Nike' and post.brand != 'Converse' %}
        <p class="None_text">예정중인 상품이 없습니다.</p>
    {% endif %}
{% endfor %}
</div>

{% endblock %}

user/templates/User/login.html
{% extends 'main/base.html' %}
{% block title %}로그인{% endblock %}
{% block content %}
    <div class="categori">
        <h2>로그인</h2>
        <form action="{%  url 'User:login' %}" method="post">

            {% csrf_token %}
            {% for field in form %}
            <div class="form-group">
                <label for="{{ field.id_for_labels }}">{{ field.label }}</label>
                {{ field }}
            </div>
            <span style="color:red">{{ field.errors }}</span>
            {% endfor %}
            <input type="submit" value="로그인" class="btn btn-primary">
        </form>
    </div>
{% endblock %}

user/templates/User/signup.html
{% extends 'main/base.html' %}
{% block title %}회원가입{% endblock %}
{% block content %}
    <div class="categori">
        <h2>회원가입</h2>
        <form action="{% url 'User:signup' %}" method="post" enctype="multipart/form-data">

            {% csrf_token %}
            {% for field in form %}
                <div class="form-group">
                    <label for="{{ field.id_for_label }}">{{ field.label }}</label>
                    {{ field }}
                </div>
            {% if field.errors %}
                <span style="color:red">{{ field.errors }}</span>
            {% endif %}
            {% endfor %}
            <input class="btn btn-primary" type="submit" value="회원가입">
        </form>
    </div>
{% endblock %}